// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnewcolunminbooktype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewcolunminbooktype));
        
        string IMigrationMetadata.Id
        {
            get { return "201805180806120_add new colunm in booktype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
