// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adduniqueforStudentCodeandBookCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduniqueforStudentCodeandBookCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201805190608199_add unique for StudentCode and BookCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
